#!/usr/bin/env bash

format_check_passed=`nix fmt 2>&1 | grep "0 files changed\|formatted 0 files\|files (0 changed)"`

if [ -z "$format_check_passed" ]; then
    echo "nixfmt changes were added. Please commit and push again."
    exit 1
else
    echo "Completed nixfmt hook."
    exit 0
fi
