#!/usr/bin/env bash
set -e

for file in "$@"; do
  output=${file%.pdf}
  output=$output"_scanned.pdf"

  pdfseparate "$file" /tmp/fake-scan-split-%04d.pdf

  for splitFile in /tmp/fake-scan-split-*.pdf; do
    splitFileBase=${splitFile%.pdf}
    scannedJpg=$splitFileBase"_scanned.jpg"

    convert -density 200 -trim -flatten "$splitFile" -attenuate 0.2 +noise Gaussian -rotate "$([ $((RANDOM % 2)) -eq 1 ] && echo -)0.$(($RANDOM % 8 + 1))" "$scannedJpg"
  done

  convert -density 200 $(ls -rt /tmp/fake-scan-split-*_scanned.jpg) -attenuate 0.2 +noise Gaussian -sharpen 0x1.0 -colorspace Gray +level 15%,100% "$output"
  echo "Scanified PDF available at $output"

  rm /tmp/fake-scan-split-*.jpg
done
